-- 创建定稿表
CREATE TABLE IF NOT EXISTS `final_drafts` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `sku` VARCHAR(255) NOT NULL UNIQUE COMMENT '产品SKU',
  `batch` VARCHAR(255) DEFAULT NULL COMMENT '批次',
  `developer` VARCHAR(255) DEFAULT NULL COMMENT '开发人',
  `carrier` VARCHAR(255) DEFAULT NULL COMMENT '载体',
  `images` TEXT DEFAULT '[]' COMMENT '图片路径JSON',
  `status` VARCHAR(50) DEFAULT 'pending' COMMENT '状态',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='定稿表';

-- 创建定稿回收站表
CREATE TABLE IF NOT EXISTS `final_draft_recycle_bin` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `draft_id` INT NOT NULL COMMENT '原定稿ID',
  `sku` VARCHAR(255) NOT NULL COMMENT '产品SKU',
  `batch` VARCHAR(255) DEFAULT NULL COMMENT '批次',
  `developer` VARCHAR(255) DEFAULT NULL COMMENT '开发人',
  `carrier` VARCHAR(255) DEFAULT NULL COMMENT '载体',
  `images` TEXT DEFAULT '[]' COMMENT '图片路径JSON',
  `status` VARCHAR(50) DEFAULT 'pending' COMMENT '状态',
  `delete_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '删除时间',
  `deleted_by` INT DEFAULT NULL COMMENT '删除人ID',
  `deleted_by_name` VARCHAR(255) DEFAULT NULL COMMENT '删除人姓名'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='定稿回收站表';
