# git-cliff 配置文件
# https://git-cliff.org/docs/configuration

[changelog]
body = """
{% if version %}\
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.message | upper_first }}{% endfor %}
{% endfor %}
"""
trim = true
render_always = true
postprocessors = [
  { pattern = '<REPO>', replace = "https://github.com/puletire9-leo/si-jue-zhi-mao-up" },
]

[git]
conventional_commits = true
filter_unconventional = true
sort_commits = "oldest"

commit_parsers = [
  { message = "^feat", group = "新增" },
  { message = "^fix", group = "修复" },
  { message = "^docs", group = "文档" },
  { message = "^refactor", group = "重构" },
  { message = "^perf", group = "性能优化" },
  { message = "^test", group = "测试" },
  { message = "^style", group = "样式" },
  { message = "^chore\\(release\\)", skip = true },
  { message = "^chore\\(deps.*\\)", skip = true },
  { message = "^chore", group = "杂项" },
  { message = "^ci", group = "CI/CD" },
  { message = "^restore", group = "新增" },
  { message = ".*", group = "其他" },
]
