-- Operations logistics: Lingxing shipment facts and normalized purchase progress.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS lingxing_shipment_plan (
    id BIGINT NOT NULL AUTO_INCREMENT,
    isp_id BIGINT NOT NULL COMMENT 'Lingxing shipment plan item ID',
    ispg_id BIGINT NULL,
    order_sn VARCHAR(64) NULL COMMENT 'Lingxing shipment plan number (R...)',
    seq VARCHAR(64) NULL COMMENT 'Lingxing shipment plan batch (RP...)',
    purchase_order_sn VARCHAR(64) NULL COMMENT 'Locally bound purchase order',
    purchase_plan_sn VARCHAR(64) NULL COMMENT 'Locally bound purchase plan',
    sku VARCHAR(128) NULL,
    msku VARCHAR(255) NULL,
    fnsku VARCHAR(128) NULL,
    product_name VARCHAR(512) NULL,
    product_id BIGINT NULL,
    pic_url VARCHAR(500) NULL,
    small_image_url VARCHAR(500) NULL,
    sid BIGINT NULL,
    sname VARCHAR(255) NULL,
    nation VARCHAR(50) NULL,
    wid BIGINT NULL,
    wname VARCHAR(255) NULL,
    packing_type TINYINT NULL,
    packing_type_name VARCHAR(50) NULL,
    shipment_plan_quantity INT NOT NULL DEFAULT 0,
    shipment_time VARCHAR(32) NULL,
    status INT NULL,
    status_name VARCHAR(64) NULL,
    is_relate_mws TINYINT NOT NULL DEFAULT 0,
    shipment_list_sn VARCHAR(128) NULL,
    shipment_mws_sn VARCHAR(128) NULL,
    batch_remark TEXT NULL,
    remark TEXT NULL,
    create_user VARCHAR(100) NULL,
    create_time_remote DATETIME NULL,
    shipping_method VARCHAR(20) NULL,
    local_created_by_user_id BIGINT NULL,
    local_created_by_username VARCHAR(100) NULL,
    local_created_by_nickname VARCHAR(100) NULL,
    local_created_time DATETIME NULL,
    raw_json LONGTEXT NULL,
    synced_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_lingxing_shipment_plan_isp (isp_id),
    KEY idx_lingxing_shipment_plan_purchase (purchase_order_sn, purchase_plan_sn),
    KEY idx_lingxing_shipment_plan_sku (sku),
    KEY idx_lingxing_shipment_plan_seq (seq)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lingxing_shipment_actual (
    id BIGINT NOT NULL AUTO_INCREMENT,
    ispr_id BIGINT NOT NULL COMMENT 'shipment_order_list unique ID',
    isp_id BIGINT NOT NULL COMMENT 'Shipment plan item ID',
    shipment_sn VARCHAR(64) NOT NULL COMMENT 'Lingxing SP number',
    seq VARCHAR(64) NULL,
    shipment_plan_sn VARCHAR(64) NULL,
    shipment_plan_quantity INT NOT NULL DEFAULT 0,
    shipment_list_quantity INT NOT NULL DEFAULT 0,
    shipment_mws_quantity INT NOT NULL DEFAULT 0,
    shipment_status INT NULL COMMENT '-1 picking, 0 pending, 1 shipped, 2 completed, 3 voided',
    shipment_status_name VARCHAR(64) NULL,
    shipment_time VARCHAR(32) NULL,
    shipment_id VARCHAR(128) NULL COMMENT 'Amazon shipment ID',
    shipment_status_mws VARCHAR(64) NULL,
    sku VARCHAR(128) NULL,
    msku VARCHAR(255) NULL,
    fnsku VARCHAR(128) NULL,
    product_name VARCHAR(512) NULL,
    method_name VARCHAR(64) NULL,
    logistics_channel_name VARCHAR(255) NULL,
    wname VARCHAR(255) NULL,
    wid BIGINT NULL,
    expected_arrival_date VARCHAR(32) NULL,
    create_user VARCHAR(100) NULL,
    create_time_remote VARCHAR(32) NULL,
    update_time_remote VARCHAR(32) NULL,
    relate_id BIGINT NULL,
    num INT NOT NULL DEFAULT 0,
    apply_num INT NOT NULL DEFAULT 0,
    sname VARCHAR(255) NULL,
    sid BIGINT NULL,
    nation VARCHAR(50) NULL,
    pic_url VARCHAR(500) NULL,
    asin VARCHAR(50) NULL,
    product_id BIGINT NULL,
    is_final TINYINT NOT NULL DEFAULT 0,
    raw_json LONGTEXT NULL,
    synced_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_lingxing_shipment_actual_ispr (ispr_id),
    KEY idx_lingxing_shipment_actual_isp (isp_id),
    KEY idx_lingxing_shipment_actual_sp (shipment_sn),
    KEY idx_lingxing_shipment_actual_sku (sku),
    KEY idx_lingxing_shipment_actual_status (shipment_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS operations_logistics_purchase_progress (
    id BIGINT NOT NULL AUTO_INCREMENT,
    business_key CHAR(64) NOT NULL COMMENT 'Purchase item biz_key',
    order_sn VARCHAR(64) NOT NULL,
    item_id BIGINT NULL,
    plan_sn VARCHAR(64) NULL,
    ppg_sn VARCHAR(64) NULL COMMENT '采购计划创建批次号（PPG）',
    sku VARCHAR(128) NOT NULL,
    stock_time DATETIME NULL,
    purchase_quantity INT NOT NULL DEFAULT 0,
    received_quantity INT NOT NULL DEFAULT 0,
    available_quantity INT NOT NULL DEFAULT 0 COMMENT '当前可用于发亚马逊的本地仓可用量',
    valid_shipped_quantity INT NOT NULL DEFAULT 0,
    progress_status VARCHAR(32) NOT NULL COMMENT 'PENDING_ARRIVAL/PENDING_SHIPMENT/SHIPPED',
    progress_value DECIMAL(5,4) NOT NULL DEFAULT 0,
    follow_up_status VARCHAR(32) NOT NULL COMMENT '待到货/待发货/已发货',
    association_status VARCHAR(32) NOT NULL DEFAULT 'LINKED',
    source_hash CHAR(64) NOT NULL,
    terminal TINYINT(1) NOT NULL DEFAULT 0,
    calculated_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_operations_logistics_business (business_key),
    KEY idx_operations_logistics_status (terminal, progress_status),
    KEY idx_operations_logistics_order (order_sn),
    KEY idx_operations_logistics_ppg (ppg_sn),
    KEY idx_operations_logistics_sku (sku)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO automation_job (
    id, job_code, job_name, description, enabled, schedule_type,
    fixed_delay_seconds, parameters_json, next_run_at
) VALUES (
    202608140001,
    'OPERATIONS_LOGISTICS_PURCHASE_PROGRESS',
    '运营物流采购进度同步',
    '领星采购及SP事实同步、三状态计算、飞书采购单进度表幂等写入',
    1,
    'MANUAL',
    NULL,
    JSON_OBJECT(),
    NULL
) ON DUPLICATE KEY UPDATE
    job_name=VALUES(job_name), description=VALUES(description),
    enabled=VALUES(enabled), schedule_type=VALUES(schedule_type),
    fixed_delay_seconds=VALUES(fixed_delay_seconds), next_run_at=NULL;
