-- =================================================================
-- Lingxing purchase data layer
-- 2026-07-10
--
-- Tables:
--   1. lingxing_purchase_plan
--   2. lingxing_purchase_order
--   3. lingxing_purchase_order_item
--
-- Purpose:
--   - Purchase plan provides planned quantity (quantity_plan).
--   - Purchase order item provides exact purchased quantity (quantity_real)
--     and received quantity (quantity_entry), used as Q1/Q2 source.
-- =================================================================

CREATE TABLE IF NOT EXISTS `lingxing_purchase_plan` (
    `id`                      BIGINT        NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    `biz_key`                 CHAR(64)      NOT NULL COMMENT 'SHA-256 business key',
    `plan_sn`                 VARCHAR(64)   NOT NULL COMMENT 'Purchase plan number',
    `ppg_sn`                  VARCHAR(64)   DEFAULT NULL COMMENT 'Purchase plan batch number',
    `status`                  INT           DEFAULT NULL COMMENT 'Plan status',
    `status_text`             VARCHAR(64)   DEFAULT NULL COMMENT 'Plan status text',
    `sku`                     VARCHAR(128)  NOT NULL COMMENT 'Local SKU',
    `product_id`              BIGINT        DEFAULT NULL COMMENT 'Local product id',
    `product_name`            VARCHAR(512)  DEFAULT NULL COMMENT 'Product name',
    `spu`                     VARCHAR(128)  DEFAULT NULL COMMENT 'SPU',
    `spu_name`                VARCHAR(512)  DEFAULT NULL COMMENT 'SPU name',
    `sid`                     BIGINT        DEFAULT NULL COMMENT 'Store id',
    `seller_name`             VARCHAR(255)  DEFAULT NULL COMMENT 'Store name',
    `marketplace_raw`         VARCHAR(64)   DEFAULT NULL COMMENT 'Marketplace text from Lingxing',
    `fnsku`                   VARCHAR(128)  DEFAULT NULL COMMENT 'FNSKU',
    `msku_json`               LONGTEXT      DEFAULT NULL COMMENT 'MSKU array JSON',
    `supplier_id`             BIGINT        DEFAULT NULL COMMENT 'Supplier id',
    `supplier_name`           VARCHAR(255)  DEFAULT NULL COMMENT 'Supplier name',
    `wid`                     BIGINT        DEFAULT NULL COMMENT 'Warehouse id',
    `warehouse_name`          VARCHAR(255)  DEFAULT NULL COMMENT 'Warehouse name',
    `purchaser_id`            BIGINT        DEFAULT NULL COMMENT 'Purchaser entity id',
    `purchaser_name`          VARCHAR(255)  DEFAULT NULL COMMENT 'Purchaser name',
    `cg_box_pcs`              INT           DEFAULT NULL COMMENT 'Pieces per carton',
    `quantity_plan`           INT           DEFAULT NULL COMMENT 'Planned purchase quantity',
    `expect_arrive_time`      DATE          DEFAULT NULL COMMENT 'Expected arrival date',
    `create_time`             DATETIME      DEFAULT NULL COMMENT 'Plan create time',
    `creator_uid`             BIGINT        DEFAULT NULL COMMENT 'Creator uid',
    `creator_real_name`       VARCHAR(255)  DEFAULT NULL COMMENT 'Creator name',
    `cg_uid`                  BIGINT        DEFAULT NULL COMMENT 'Purchase operator uid',
    `cg_opt_username`         VARCHAR(255)  DEFAULT NULL COMMENT 'Purchase operator name',
    `remark`                  TEXT          DEFAULT NULL COMMENT 'Product remark',
    `plan_remark`             TEXT          DEFAULT NULL COMMENT 'Plan remark',
    `is_combo`                TINYINT       DEFAULT NULL COMMENT 'Combo product flag',
    `is_aux`                  TINYINT       DEFAULT NULL COMMENT 'Auxiliary material flag',
    `is_related_process_plan` TINYINT       DEFAULT NULL COMMENT 'Related process plan flag',
    `attribute_json`          LONGTEXT      DEFAULT NULL COMMENT 'Attribute JSON',
    `file_json`               LONGTEXT      DEFAULT NULL COMMENT 'Attachment JSON',
    `perm_uid_json`           LONGTEXT      DEFAULT NULL COMMENT 'Permission uid JSON',
    `perm_username_json`      LONGTEXT      DEFAULT NULL COMMENT 'Permission username JSON',
    `source_run_id`           VARCHAR(64)   DEFAULT NULL COMMENT 'Source run id',
    `raw_json`                LONGTEXT      DEFAULT NULL COMMENT 'Raw API row JSON',
    `synced_at`               DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT 'Synced time',
    `created_at`              DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    `updated_at`              DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',

    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_biz_key` (`biz_key`),
    KEY `idx_plan_sn` (`plan_sn`),
    KEY `idx_ppg_sn` (`ppg_sn`),
    KEY `idx_sku_sid` (`sku`, `sid`),
    KEY `idx_status` (`status`),
    KEY `idx_create_time` (`create_time`),
    KEY `idx_expect_arrive_time` (`expect_arrive_time`),
    KEY `idx_source_run` (`source_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Lingxing purchase plan fact table';

CREATE TABLE IF NOT EXISTS `lingxing_purchase_order` (
    `id`                       BIGINT        NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    `biz_key`                  CHAR(64)      NOT NULL COMMENT 'SHA-256 business key',
    `order_sn`                 VARCHAR(64)   NOT NULL COMMENT 'Purchase order number',
    `custom_order_sn`          VARCHAR(128)  DEFAULT NULL COMMENT 'Custom purchase order number',
    `supplier_id`              BIGINT        DEFAULT NULL COMMENT 'Supplier id',
    `supplier_name`            VARCHAR(255)  DEFAULT NULL COMMENT 'Supplier name',
    `opt_uid`                  BIGINT        DEFAULT NULL COMMENT 'Operator uid',
    `opt_realname`             VARCHAR(255)  DEFAULT NULL COMMENT 'Operator name',
    `last_uid`                 BIGINT        DEFAULT NULL COMMENT 'Last operator uid',
    `last_realname`            VARCHAR(255)  DEFAULT NULL COMMENT 'Last operator name',
    `auditor_uid`              BIGINT        DEFAULT NULL COMMENT 'Auditor uid',
    `auditor_realname`         VARCHAR(255)  DEFAULT NULL COMMENT 'Auditor name',
    `create_time`              DATETIME      DEFAULT NULL COMMENT 'Create time',
    `order_time`               DATETIME      DEFAULT NULL COMMENT 'Order time',
    `auditor_time`             DATETIME      DEFAULT NULL COMMENT 'Audit time',
    `last_time`                DATETIME      DEFAULT NULL COMMENT 'Last update time',
    `update_time`              DATETIME      DEFAULT NULL COMMENT 'Purchase order update time',
    `status`                   INT           DEFAULT NULL COMMENT 'Purchase order status',
    `status_text`              VARCHAR(64)   DEFAULT NULL COMMENT 'Purchase order status text',
    `status_shipped`           INT           DEFAULT NULL COMMENT 'Arrival status',
    `status_shipped_text`      VARCHAR(64)   DEFAULT NULL COMMENT 'Arrival status text',
    `pay_status`               INT           DEFAULT NULL COMMENT 'Payment status',
    `pay_status_text`          VARCHAR(64)   DEFAULT NULL COMMENT 'Payment status text',
    `purchase_type`            VARCHAR(32)   DEFAULT NULL COMMENT 'Purchase type',
    `purchase_type_text`       VARCHAR(64)   DEFAULT NULL COMMENT 'Purchase type text',
    `purchase_currency`        VARCHAR(16)   DEFAULT NULL COMMENT 'Purchase currency',
    `purchase_rate`            DECIMAL(18,6) DEFAULT NULL COMMENT 'Purchase rate',
    `amount_total`             DECIMAL(18,4) DEFAULT NULL COMMENT 'Goods total amount',
    `total_price`              DECIMAL(18,4) DEFAULT NULL COMMENT 'Total price',
    `payment`                  DECIMAL(18,4) DEFAULT NULL COMMENT 'Manual payable amount',
    `other_fee`                DECIMAL(18,4) DEFAULT NULL COMMENT 'Other fee',
    `shipping_price`           DECIMAL(18,4) DEFAULT NULL COMMENT 'Shipping fee',
    `quantity_total`           INT           DEFAULT NULL COMMENT 'Purchase total quantity',
    `quantity_real`            INT           DEFAULT NULL COMMENT 'Actual purchase quantity',
    `quantity_entry`           INT           DEFAULT NULL COMMENT 'Received entry quantity',
    `quantity_receive`         INT           DEFAULT NULL COMMENT 'Pending receive quantity',
    `wid`                      BIGINT        DEFAULT NULL COMMENT 'Warehouse id',
    `ware_house_name`          VARCHAR(255)  DEFAULT NULL COMMENT 'Warehouse name',
    `ware_house_bak_name`      VARCHAR(255)  DEFAULT NULL COMMENT 'Warehouse backup name',
    `purchaser_id`             BIGINT        DEFAULT NULL COMMENT 'Purchaser entity id',
    `settlement_method`        INT           DEFAULT NULL COMMENT 'Settlement method',
    `settlement_description`   VARCHAR(255)  DEFAULT NULL COMMENT 'Settlement description',
    `remark`                   TEXT          DEFAULT NULL COMMENT 'Remark',
    `reason`                   TEXT          DEFAULT NULL COMMENT 'Cancel reason',
    `principal_uids_json`      LONGTEXT      DEFAULT NULL COMMENT 'Principal users JSON',
    `custom_fields_json`       LONGTEXT      DEFAULT NULL COMMENT 'Custom fields JSON',
    `logistics_info_json`      LONGTEXT      DEFAULT NULL COMMENT 'Logistics info JSON',
    `source_run_id`            VARCHAR(64)   DEFAULT NULL COMMENT 'Source run id',
    `raw_json`                 LONGTEXT      DEFAULT NULL COMMENT 'Raw API row JSON',
    `synced_at`                DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT 'Synced time',
    `created_at`               DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    `updated_at`               DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',

    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_biz_key` (`biz_key`),
    UNIQUE KEY `uk_order_sn` (`order_sn`),
    KEY `idx_status` (`status`, `status_shipped`),
    KEY `idx_order_time` (`order_time`),
    KEY `idx_update_time` (`update_time`),
    KEY `idx_supplier` (`supplier_id`),
    KEY `idx_source_run` (`source_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Lingxing purchase order fact table';

CREATE TABLE IF NOT EXISTS `lingxing_purchase_order_item` (
    `id`                          BIGINT        NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    `biz_key`                     CHAR(64)      NOT NULL COMMENT 'SHA-256 business key',
    `order_sn`                    VARCHAR(64)   NOT NULL COMMENT 'Purchase order number',
    `custom_order_sn`             VARCHAR(128)  DEFAULT NULL COMMENT 'Custom purchase order number',
    `item_id`                     BIGINT        DEFAULT NULL COMMENT 'Purchase order item id',
    `plan_sn`                     VARCHAR(64)   DEFAULT NULL COMMENT 'Purchase plan number',
    `relation_purchase_plan_json` LONGTEXT      DEFAULT NULL COMMENT 'Related purchase plan JSON',
    `product_id`                  BIGINT        DEFAULT NULL COMMENT 'Local product id',
    `product_name`                VARCHAR(512)  DEFAULT NULL COMMENT 'Product name',
    `sku`                         VARCHAR(128)  NOT NULL COMMENT 'Local SKU',
    `fnsku`                       VARCHAR(128)  DEFAULT NULL COMMENT 'FNSKU',
    `sid`                         BIGINT        DEFAULT NULL COMMENT 'Store id',
    `msku_json`                   LONGTEXT      DEFAULT NULL COMMENT 'MSKU array JSON',
    `wid`                         BIGINT        DEFAULT NULL COMMENT 'Warehouse id',
    `ware_house_name`             VARCHAR(255)  DEFAULT NULL COMMENT 'Warehouse name',
    `model`                       VARCHAR(255)  DEFAULT NULL COMMENT 'Model',
    `price`                       DECIMAL(18,4) DEFAULT NULL COMMENT 'Tax-inclusive unit price',
    `amount`                      DECIMAL(18,4) DEFAULT NULL COMMENT 'Tax-inclusive amount',
    `quantity_plan`               INT           DEFAULT NULL COMMENT 'Planned purchase quantity',
    `quantity_real`               INT           DEFAULT NULL COMMENT 'Actual purchase quantity',
    `quantity_entry`              INT           DEFAULT NULL COMMENT 'Received entry quantity',
    `quantity_receive`            INT           DEFAULT NULL COMMENT 'Pending receive quantity',
    `quantity_return`             INT           DEFAULT NULL COMMENT 'Return quantity',
    `quantity_exchange`           INT           DEFAULT NULL COMMENT 'Exchange quantity',
    `quantity_qc`                 INT           DEFAULT NULL COMMENT 'QC quantity',
    `quantity_qc_prepare`         INT           DEFAULT NULL COMMENT 'Pending QC quantity',
    `expect_arrive_time`          DATE          DEFAULT NULL COMMENT 'Expected arrival date',
    `cases_num`                   INT           DEFAULT NULL COMMENT 'Carton count',
    `quantity_per_case`           INT           DEFAULT NULL COMMENT 'Quantity per carton',
    `is_delete`                   TINYINT       DEFAULT NULL COMMENT 'Deleted item flag',
    `spu`                         VARCHAR(128)  DEFAULT NULL COMMENT 'SPU',
    `spu_name`                    VARCHAR(512)  DEFAULT NULL COMMENT 'SPU name',
    `attribute_json`              LONGTEXT      DEFAULT NULL COMMENT 'Attribute JSON',
    `custom_fields_json`          LONGTEXT      DEFAULT NULL COMMENT 'Custom fields JSON',
    `remark`                      TEXT          DEFAULT NULL COMMENT 'Remark',
    `source_run_id`               VARCHAR(64)   DEFAULT NULL COMMENT 'Source run id',
    `raw_json`                    LONGTEXT      DEFAULT NULL COMMENT 'Raw API item JSON',
    `synced_at`                   DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT 'Synced time',
    `created_at`                  DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    `updated_at`                  DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',

    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_biz_key` (`biz_key`),
    KEY `idx_order_sn` (`order_sn`),
    KEY `idx_plan_sn` (`plan_sn`),
    KEY `idx_sku_sid` (`sku`, `sid`),
    KEY `idx_quantity_real` (`quantity_real`),
    KEY `idx_quantity_entry` (`quantity_entry`),
    KEY `idx_expect_arrive_time` (`expect_arrive_time`),
    KEY `idx_is_delete` (`is_delete`),
    KEY `idx_source_run` (`source_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Lingxing purchase order item fact table';
