-- product_performance_actual
-- ③线真实战绩表：存储 591+ 历史赢家与半自动打标结果

CREATE TABLE IF NOT EXISTS `product_performance_actual` (
    `id` BIGINT NOT NULL COMMENT '雪花ID',
    `asin` VARCHAR(20) NOT NULL COMMENT 'ASIN',
    `parent_asin` VARCHAR(20) DEFAULT NULL COMMENT '父ASIN',
    `sku` VARCHAR(100) DEFAULT NULL COMMENT 'SKU',
    `marketplace` VARCHAR(10) NOT NULL COMMENT '站点: UK/DE/IT/US',
    `price` DECIMAL(10, 2) DEFAULT NULL COMMENT '售价(清洗货币符号)',
    `sales_volume` INT DEFAULT NULL COMMENT '销量',
    `category_rank_main` VARCHAR(200) DEFAULT NULL COMMENT '大类排名原文',
    `category_main` VARCHAR(100) DEFAULT NULL COMMENT '大类名',
    `category_rank_sub` VARCHAR(200) DEFAULT NULL COMMENT '小类排名原文',
    `category_sub` VARCHAR(150) DEFAULT NULL COMMENT '小类名',
    `acoas` DECIMAL(8, 4) DEFAULT NULL COMMENT '广告销售成本占比',
    `natural_clicks` INT DEFAULT NULL COMMENT '自然点击量',
    `ctr` DECIMAL(6, 4) DEFAULT NULL COMMENT 'CTR 百分比转小数',
    `ad_cvr` DECIMAL(6, 4) DEFAULT NULL COMMENT '广告 CVR 百分比转小数',
    `natural_orders` INT DEFAULT NULL COMMENT '自然订单量',
    `fba_available` INT DEFAULT NULL COMMENT 'FBA 可售',
    `refund_rate` DECIMAL(6, 4) DEFAULT NULL COMMENT '退款率 百分比转小数',
    `product_name` VARCHAR(500) DEFAULT NULL COMMENT '中文品名',
    `title` VARCHAR(1000) DEFAULT NULL COMMENT '英文标题',
    `archetype` VARCHAR(8) DEFAULT NULL COMMENT '原型: STD/CUSTOM',
    `element` VARCHAR(100) DEFAULT NULL COMMENT '元素',
    `carrier` VARCHAR(100) DEFAULT NULL COMMENT '载体',
    `listing_tags` VARCHAR(200) DEFAULT NULL COMMENT '原始标签',
    `is_eliminated` TINYINT DEFAULT 0 COMMENT '标签含淘汰',
    `is_green` TINYINT DEFAULT 0 COMMENT '标签含绿标',
    `bsr_id` VARCHAR(100) DEFAULT NULL COMMENT '大类 slug',
    `source_batch` VARCHAR(50) DEFAULT NULL COMMENT '导入批次',
    `imported_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '导入时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_asin_marketplace` (`asin`, `marketplace`),
    KEY `idx_archetype` (`archetype`),
    KEY `idx_category_sub` (`category_sub`(64)),
    KEY `idx_is_eliminated` (`is_eliminated`),
    KEY `idx_is_green` (`is_green`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='自有真实战绩(tier1真值,591赢家)';
