-- =================================================================
-- Lingxing SKU data layer
-- 2026-07-09
--
-- Tables:
--   1. lingxing_data_sync_run
--   2. lingxing_sku_store_snapshot
--   3. lingxing_target_sku_pool
--   4. lingxing_sku_weekly_performance
--   5. lingxing_sku_monthly_performance
--
-- Notes:
--   - SKU/store/country granularity must keep sid + store_name.
--   - SKU pool source stores must include status IN (1,2).
--   - Product performance sync must use summary_field=sku and
--     is_recently_enum=false.
-- =================================================================

CREATE TABLE IF NOT EXISTS `lingxing_data_sync_run` (
    `id`              BIGINT       NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    `run_id`          VARCHAR(64)  NOT NULL COMMENT 'Stable run id',
    `run_type`        VARCHAR(64)  NOT NULL COMMENT 'SNAPSHOT / TARGET_POOL / WEEKLY / MONTHLY',
    `marketplace`     VARCHAR(8)   DEFAULT NULL COMMENT 'UK / DE / ALL',
    `mid`             INT          DEFAULT NULL COMMENT 'Lingxing marketplace id',
    `start_date`      DATE         DEFAULT NULL COMMENT 'Data window start',
    `end_date`        DATE         DEFAULT NULL COMMENT 'Data window end',
    `snapshot_week`   VARCHAR(8)   DEFAULT NULL COMMENT 'yyyy-Www',
    `year_month`      VARCHAR(7)   DEFAULT NULL COMMENT 'yyyy-MM',
    `sid_count`       INT          DEFAULT 0 COMMENT 'Requested sid count',
    `sku_count`       INT          DEFAULT 0 COMMENT 'Requested sku count',
    `page_count`      INT          DEFAULT 0 COMMENT 'Fetched pages',
    `fetched_count`   INT          DEFAULT 0 COMMENT 'Fetched rows',
    `upserted_count`  INT          DEFAULT 0 COMMENT 'Upserted rows',
    `status`          VARCHAR(32)  NOT NULL DEFAULT 'RUNNING' COMMENT 'RUNNING / SUCCESS / FAILED',
    `error_message`   TEXT         DEFAULT NULL COMMENT 'Error message',
    `request_json`    LONGTEXT     DEFAULT NULL COMMENT 'Request payload snapshot',
    `started_at`      DATETIME     DEFAULT CURRENT_TIMESTAMP COMMENT 'Start time',
    `finished_at`     DATETIME     DEFAULT NULL COMMENT 'Finish time',
    `created_at`      DATETIME     DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    `updated_at`      DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',

    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_run_id` (`run_id`),
    KEY `idx_run_type_status` (`run_type`, `status`),
    KEY `idx_window` (`start_date`, `end_date`),
    KEY `idx_snapshot_week` (`snapshot_week`),
    KEY `idx_year_month` (`year_month`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Lingxing data sync run log';

CREATE TABLE IF NOT EXISTS `lingxing_sku_store_snapshot` (
    `id`              BIGINT        NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    `biz_key`         CHAR(64)      NOT NULL COMMENT 'SHA-256 business key',
    `snapshot_week`   VARCHAR(8)    NOT NULL COMMENT 'yyyy-Www',
    `snapshot_date`   DATE          NOT NULL COMMENT 'Snapshot date',
    `marketplace`     VARCHAR(8)    NOT NULL COMMENT 'UK / DE',
    `mid`             INT           NOT NULL COMMENT 'Lingxing marketplace id',
    `sid`             BIGINT        NOT NULL COMMENT 'Lingxing store id',
    `store_name`      VARCHAR(255)  DEFAULT NULL COMMENT 'Store name',
    `country`         VARCHAR(32)   DEFAULT NULL COMMENT 'Country from price_list',
    `sku`             VARCHAR(128)  NOT NULL COMMENT 'Local SKU',
    `seller_sku`      VARCHAR(255)  DEFAULT NULL COMMENT 'MSKU',
    `asin`            VARCHAR(32)   DEFAULT NULL COMMENT 'ASIN',
    `parent_asin`     VARCHAR(32)   DEFAULT NULL COMMENT 'Parent ASIN',
    `product_name`    VARCHAR(512)  DEFAULT NULL COMMENT 'Listing title',
    `local_name`      VARCHAR(512)  DEFAULT NULL COMMENT 'Local product name',
    `price`           DECIMAL(18,4) DEFAULT NULL COMMENT 'Listing price',
    `listing_status`  INT           DEFAULT NULL COMMENT 'Listing status from price_list.status',
    `is_delete`       INT           DEFAULT NULL COMMENT 'price_list.is_delete',
    `tag_ids`         VARCHAR(512)  DEFAULT NULL COMMENT 'Listing tag ids',
    `tags`            VARCHAR(512)  DEFAULT NULL COMMENT 'Listing tag names',
    `pic_url`         VARCHAR(1000) DEFAULT NULL COMMENT 'Picture URL',
    `source_run_id`   VARCHAR(64)   DEFAULT NULL COMMENT 'Source run id',
    `raw_json`        LONGTEXT      DEFAULT NULL COMMENT 'Raw row JSON',
    `synced_at`       DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT 'Synced time',
    `created_at`      DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    `updated_at`      DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',

    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_biz_key` (`biz_key`),
    KEY `idx_snapshot_market` (`snapshot_week`, `marketplace`),
    KEY `idx_store_country` (`sid`, `country`),
    KEY `idx_sid_sku` (`sid`, `sku`),
    KEY `idx_sku` (`sku`),
    KEY `idx_asin` (`asin`),
    KEY `idx_source_run` (`source_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Lingxing full SKU store weekly snapshot';

CREATE TABLE IF NOT EXISTS `lingxing_target_sku_pool` (
    `id`              BIGINT        NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    `biz_key`         CHAR(64)      NOT NULL COMMENT 'SHA-256 business key',
    `snapshot_week`   VARCHAR(8)    NOT NULL COMMENT 'yyyy-Www',
    `marketplace`     VARCHAR(8)    NOT NULL COMMENT 'UK / DE',
    `mid`             INT           NOT NULL COMMENT 'Lingxing marketplace id',
    `sid`             BIGINT        NOT NULL COMMENT 'Lingxing store id',
    `store_name`      VARCHAR(255)  DEFAULT NULL COMMENT 'Store name',
    `country`         VARCHAR(32)   DEFAULT NULL COMMENT 'Country from price_list',
    `sku`             VARCHAR(128)  NOT NULL COMMENT 'Local SKU',
    `seller_sku`      VARCHAR(255)  DEFAULT NULL COMMENT 'MSKU',
    `asin`            VARCHAR(32)   DEFAULT NULL COMMENT 'ASIN',
    `parent_asin`     VARCHAR(32)   DEFAULT NULL COMMENT 'Parent ASIN',
    `product_name`    VARCHAR(512)  DEFAULT NULL COMMENT 'Listing title',
    `tag_ids`         VARCHAR(512)  DEFAULT NULL COMMENT 'Matched tag ids',
    `tags`            VARCHAR(512)  DEFAULT NULL COMMENT 'Matched tag names',
    `is_target`       TINYINT       NOT NULL DEFAULT 1 COMMENT 'Target SKU flag',
    `filter_reason`   VARCHAR(255)  DEFAULT NULL COMMENT 'Filter reason',
    `first_seen_week` VARCHAR(8)    DEFAULT NULL COMMENT 'First seen week',
    `last_seen_week`  VARCHAR(8)    DEFAULT NULL COMMENT 'Last seen week',
    `is_active`       TINYINT       NOT NULL DEFAULT 1 COMMENT 'Active in current snapshot',
    `source_run_id`   VARCHAR(64)   DEFAULT NULL COMMENT 'Source run id',
    `raw_json`        LONGTEXT      DEFAULT NULL COMMENT 'Raw row JSON',
    `created_at`      DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    `updated_at`      DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',

    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_biz_key` (`biz_key`),
    KEY `idx_snapshot_market` (`snapshot_week`, `marketplace`),
    KEY `idx_store_country` (`sid`, `country`),
    KEY `idx_sid_sku` (`sid`, `sku`),
    KEY `idx_sku` (`sku`),
    KEY `idx_active` (`snapshot_week`, `is_active`),
    KEY `idx_source_run` (`source_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Lingxing target tag SKU pool with store granularity';

CREATE TABLE IF NOT EXISTS `lingxing_sku_weekly_performance` (
    `id`                         BIGINT        NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    `biz_key`                    CHAR(64)      NOT NULL COMMENT 'SHA-256 business key',
    `week_start`                 DATE          NOT NULL COMMENT 'Week window start',
    `week_end`                   DATE          NOT NULL COMMENT 'Week window end',
    `year_month`                 VARCHAR(7)    NOT NULL COMMENT 'yyyy-MM',
    `month_week_no`              INT           NOT NULL COMMENT 'Business week number in month: 1-4',
    `iso_year`                   INT           DEFAULT NULL COMMENT 'ISO week based year',
    `iso_week`                   INT           DEFAULT NULL COMMENT 'ISO week number',
    `marketplace`                VARCHAR(8)    NOT NULL COMMENT 'UK / DE',
    `mid`                        INT           NOT NULL COMMENT 'Lingxing marketplace id',
    `sid_scope`                  VARCHAR(500)  DEFAULT NULL COMMENT 'Actual sid set returned by Lingxing row',
    `sid`                        BIGINT        DEFAULT NULL COMMENT 'Single Lingxing store id when row is single-store',
    `store_name`                 VARCHAR(255)  DEFAULT NULL COMMENT 'Store name',
    `sku`                        VARCHAR(128)  NOT NULL COMMENT 'Local SKU',
    `seller_sku`                 VARCHAR(255)  DEFAULT NULL COMMENT 'MSKU',
    `asin`                       VARCHAR(32)   DEFAULT NULL COMMENT 'ASIN',
    `parent_asin`                VARCHAR(32)   DEFAULT NULL COMMENT 'Parent ASIN',
    `product_name`               VARCHAR(512)  DEFAULT NULL COMMENT 'Listing title',
    `local_name`                 VARCHAR(512)  DEFAULT NULL COMMENT 'Local product name',
    `tag_ids`                    VARCHAR(512)  DEFAULT NULL COMMENT 'Matched tag ids',
    `tags`                       VARCHAR(512)  DEFAULT NULL COMMENT 'Matched tag names',
    `is_target_sku`              TINYINT       NOT NULL DEFAULT 0 COMMENT 'In target SKU pool',

    `volume`                     INT           DEFAULT NULL COMMENT 'Sales quantity',
    `order_items`                INT           DEFAULT NULL COMMENT 'Order items',
    `amount`                     DECIMAL(18,4) DEFAULT NULL COMMENT 'Sales amount',
    `net_amount`                 DECIMAL(18,4) DEFAULT NULL COMMENT 'Net sales amount',
    `avg_volume`                 DECIMAL(18,4) DEFAULT NULL COMMENT 'Average sales quantity',
    `avg_custom_price`           DECIMAL(18,4) DEFAULT NULL COMMENT 'Average selling price',
    `promotion_volume`           INT           DEFAULT NULL COMMENT 'Promotion sales quantity',
    `promotion_amount`           DECIMAL(18,4) DEFAULT NULL COMMENT 'Promotion amount',

    `gross_profit`               DECIMAL(18,4) DEFAULT NULL COMMENT 'Settlement gross profit',
    `predict_gross_profit`       DECIMAL(18,4) DEFAULT NULL COMMENT 'Predicted/order gross profit',
    `gross_margin`               DECIMAL(18,6) DEFAULT NULL COMMENT 'Gross margin',
    `roi`                        DECIMAL(18,6) DEFAULT NULL COMMENT 'ROI',

    `spend`                      DECIMAL(18,4) DEFAULT NULL COMMENT 'Ad spend',
    `tacos`                      DECIMAL(18,6) DEFAULT NULL COMMENT 'TACOS',
    `acos`                       DECIMAL(18,6) DEFAULT NULL COMMENT 'ACOS',
    `acoas`                      DECIMAL(18,6) DEFAULT NULL COMMENT 'ACOAS',
    `ad_order_quantity`          INT           DEFAULT NULL COMMENT 'Ad orders',
    `ad_sales_amount`            DECIMAL(18,4) DEFAULT NULL COMMENT 'Ad sales amount',

    `sessions_total`             INT           DEFAULT NULL COMMENT 'Sessions total',
    `page_views_total`           INT           DEFAULT NULL COMMENT 'Page views total',
    `clicks`                     INT           DEFAULT NULL COMMENT 'Clicks',
    `impressions`                INT           DEFAULT NULL COMMENT 'Impressions',
    `ctr`                        DECIMAL(18,6) DEFAULT NULL COMMENT 'CTR',
    `cvr`                        DECIMAL(18,6) DEFAULT NULL COMMENT 'CVR',

    `afn_fulfillable_quantity`   INT           DEFAULT NULL COMMENT 'FBA fulfillable quantity',
    `fbm_quantity`               INT           DEFAULT NULL COMMENT 'FBM quantity',
    `available_days`             INT           DEFAULT NULL COMMENT 'Available days',
    `fbm_available_days`         INT           DEFAULT NULL COMMENT 'FBM available days',
    `stock_up_num`               INT           DEFAULT NULL COMMENT 'Stock-up quantity',
    `reserved_fc_transfers`      INT           DEFAULT NULL COMMENT 'Reserved FC transfers',
    `reserved_customerorders`    INT           DEFAULT NULL COMMENT 'Reserved customer orders',
    `reserved_fc_processing`     INT           DEFAULT NULL COMMENT 'Reserved FC processing',

    `reviews_count`              INT           DEFAULT NULL COMMENT 'Reviews count',
    `avg_star`                   DECIMAL(18,4) DEFAULT NULL COMMENT 'Average star',
    `return_count`               INT           DEFAULT NULL COMMENT 'Refund count',
    `return_rate`                DECIMAL(18,6) DEFAULT NULL COMMENT 'Refund rate',
    `return_goods_count`         INT           DEFAULT NULL COMMENT 'Return goods count',
    `return_goods_rate`          DECIMAL(18,6) DEFAULT NULL COMMENT 'Return goods rate',

    `currency_code`              VARCHAR(16)   DEFAULT NULL COMMENT 'Currency code',
    `source_run_id`              VARCHAR(64)   DEFAULT NULL COMMENT 'Source run id',
    `raw_json`                   LONGTEXT      DEFAULT NULL COMMENT 'Raw API row JSON',
    `synced_at`                  DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT 'Synced time',
    `created_at`                 DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    `updated_at`                 DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',

    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_biz_key` (`biz_key`),
    KEY `idx_week_market` (`week_start`, `week_end`, `marketplace`),
    KEY `idx_month` (`year_month`, `month_week_no`),
    KEY `idx_sid_scope` (`sid_scope`),
    KEY `idx_sid_sku` (`sid`, `sku`),
    KEY `idx_sku` (`sku`),
    KEY `idx_asin` (`asin`),
    KEY `idx_target` (`is_target_sku`),
    KEY `idx_source_run` (`source_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Lingxing SKU weekly performance fact table';

CREATE TABLE IF NOT EXISTS `lingxing_sku_monthly_performance` (
    `id`                         BIGINT        NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    `biz_key`                    CHAR(64)      NOT NULL COMMENT 'SHA-256 business key',
    `year_month`                 VARCHAR(7)    NOT NULL COMMENT 'yyyy-MM',
    `month_start`                DATE          NOT NULL COMMENT 'Month window start',
    `month_end`                  DATE          NOT NULL COMMENT 'Month window end',
    `weeks_count`                INT           NOT NULL DEFAULT 0 COMMENT 'Aggregated week count',
    `source_weeks`               VARCHAR(255)  DEFAULT NULL COMMENT 'Source week windows',
    `marketplace`                VARCHAR(8)    NOT NULL COMMENT 'UK / DE',
    `mid`                        INT           NOT NULL COMMENT 'Lingxing marketplace id',
    `sid_scope`                  VARCHAR(500)  DEFAULT NULL COMMENT 'Actual sid set returned by Lingxing row',
    `sid`                        BIGINT        DEFAULT NULL COMMENT 'Single Lingxing store id when row is single-store',
    `store_name`                 VARCHAR(255)  DEFAULT NULL COMMENT 'Store name',
    `sku`                        VARCHAR(128)  NOT NULL COMMENT 'Local SKU',
    `seller_sku`                 VARCHAR(255)  DEFAULT NULL COMMENT 'MSKU',
    `asin`                       VARCHAR(32)   DEFAULT NULL COMMENT 'ASIN',
    `parent_asin`                VARCHAR(32)   DEFAULT NULL COMMENT 'Parent ASIN',
    `product_name`               VARCHAR(512)  DEFAULT NULL COMMENT 'Listing title',
    `local_name`                 VARCHAR(512)  DEFAULT NULL COMMENT 'Local product name',
    `tag_ids`                    VARCHAR(512)  DEFAULT NULL COMMENT 'Matched tag ids',
    `tags`                       VARCHAR(512)  DEFAULT NULL COMMENT 'Matched tag names',
    `is_target_sku`              TINYINT       NOT NULL DEFAULT 0 COMMENT 'In target SKU pool',

    `volume`                     INT           DEFAULT NULL COMMENT 'Monthly sales quantity',
    `order_items`                INT           DEFAULT NULL COMMENT 'Monthly order items',
    `amount`                     DECIMAL(18,4) DEFAULT NULL COMMENT 'Monthly sales amount',
    `net_amount`                 DECIMAL(18,4) DEFAULT NULL COMMENT 'Monthly net amount',
    `promotion_volume`           INT           DEFAULT NULL COMMENT 'Monthly promotion sales',
    `promotion_amount`           DECIMAL(18,4) DEFAULT NULL COMMENT 'Monthly promotion amount',
    `gross_profit`               DECIMAL(18,4) DEFAULT NULL COMMENT 'Monthly settlement gross profit',
    `predict_gross_profit`       DECIMAL(18,4) DEFAULT NULL COMMENT 'Monthly predicted gross profit',
    `spend`                      DECIMAL(18,4) DEFAULT NULL COMMENT 'Monthly ad spend',
    `ad_order_quantity`          INT           DEFAULT NULL COMMENT 'Monthly ad orders',
    `ad_sales_amount`            DECIMAL(18,4) DEFAULT NULL COMMENT 'Monthly ad sales amount',
    `sessions_total`             INT           DEFAULT NULL COMMENT 'Monthly sessions total',
    `page_views_total`           INT           DEFAULT NULL COMMENT 'Monthly page views total',
    `clicks`                     INT           DEFAULT NULL COMMENT 'Monthly clicks',
    `impressions`                INT           DEFAULT NULL COMMENT 'Monthly impressions',
    `return_count`               INT           DEFAULT NULL COMMENT 'Monthly refund count',
    `return_goods_count`         INT           DEFAULT NULL COMMENT 'Monthly return goods count',

    `avg_weekly_volume`          DECIMAL(18,4) DEFAULT NULL COMMENT 'Average weekly volume',
    `avg_price`                  DECIMAL(18,4) DEFAULT NULL COMMENT 'Average price',
    `gross_margin`               DECIMAL(18,6) DEFAULT NULL COMMENT 'Gross margin',
    `tacos`                      DECIMAL(18,6) DEFAULT NULL COMMENT 'TACOS',
    `acos`                       DECIMAL(18,6) DEFAULT NULL COMMENT 'ACOS',
    `ctr`                        DECIMAL(18,6) DEFAULT NULL COMMENT 'CTR',
    `cvr`                        DECIMAL(18,6) DEFAULT NULL COMMENT 'CVR',
    `return_rate`                DECIMAL(18,6) DEFAULT NULL COMMENT 'Refund rate',
    `roi`                        DECIMAL(18,6) DEFAULT NULL COMMENT 'ROI',

    `currency_code`              VARCHAR(16)   DEFAULT NULL COMMENT 'Currency code',
    `source_run_id`              VARCHAR(64)   DEFAULT NULL COMMENT 'Source run id',
    `aggregate_json`             LONGTEXT      DEFAULT NULL COMMENT 'Aggregation detail JSON',
    `generated_at`               DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT 'Generated time',
    `created_at`                 DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    `updated_at`                 DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',

    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_biz_key` (`biz_key`),
    KEY `idx_month_market` (`year_month`, `marketplace`),
    KEY `idx_sid_scope` (`sid_scope`),
    KEY `idx_sid_sku` (`sid`, `sku`),
    KEY `idx_sku` (`sku`),
    KEY `idx_asin` (`asin`),
    KEY `idx_target` (`is_target_sku`),
    KEY `idx_source_run` (`source_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Lingxing SKU monthly performance aggregate table';
