-- analysis-baseline 数据分析基线层表结构
-- 需要手动在开发/生产数据库执行后，物化接口和后续基线/商品族功能才能写入。
-- 当前实时画像接口可以不依赖这些表实时聚合。
-- POST /api/v1/shop-profile/compute 依赖 shop_profile_snapshot / shop_profile_category。
-- GET/POST /api/v1/shop-profile/positioning* 依赖 shop_profile_snapshot / shop_profile_baseline* / shop_profile_positioning_result。

CREATE TABLE IF NOT EXISTS shop_profile_snapshot (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    marketplace VARCHAR(16) NOT NULL COMMENT '站点/国家',
    seller_name VARCHAR(255) NOT NULL COMMENT '店铺名',
    seller_id VARCHAR(128) NULL COMMENT '卖家ID',
    batch_date VARCHAR(64) NOT NULL COMMENT '数据批次',
    variation_mode VARCHAR(8) NOT NULL DEFAULT 'Y' COMMENT 'Y=不含变体父体口径,N=含变体',
    product_count INT NOT NULL DEFAULT 0 COMMENT '商品数',
    a_count INT NOT NULL DEFAULT 0 COMMENT 'A层商品数',
    b_count INT NOT NULL DEFAULT 0 COMMENT 'B层商品数',
    c_count INT NOT NULL DEFAULT 0 COMMENT 'C层商品数',
    d_count INT NOT NULL DEFAULT 0 COMMENT 'D层商品数',
    unknown_count INT NOT NULL DEFAULT 0 COMMENT '未知销量商品数',
    ab_count INT NOT NULL DEFAULT 0 COMMENT 'A+B 强候选池',
    abc_count INT NOT NULL DEFAULT 0 COMMENT 'A+B+C 稳定盘',
    a_ratio DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT 'A占比',
    ab_ratio DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT 'A+B占比',
    abc_ratio DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT 'A+B+C占比',
    d_ratio DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT 'D占比',
    top_a_category VARCHAR(255) NULL COMMENT 'A层最高频类目',
    top_abc_category VARCHAR(255) NULL COMMENT 'ABC最高频类目',
    top_d_category VARCHAR(255) NULL COMMENT 'D层最高频类目',
    new_count INT NULL COMMENT '新商品数，预留',
    growing_count INT NULL COMMENT '成长商品数，预留',
    mature_count INT NULL COMMENT '成熟商品数，预留',
    d_new_count INT NULL COMMENT '新D商品数，预留',
    d_old_count INT NULL COMMENT '老D商品数，预留',
    d_abc_overlap_ratio DECIMAL(10,4) NULL COMMENT 'D与ABC类目重合度，预留',
    method_hit_summary_json JSON NULL COMMENT '方法卡命中摘要，预留',
    profile_type VARCHAR(64) NULL COMMENT '结构标签',
    source_table VARCHAR(64) NOT NULL DEFAULT 'deng_zong_shop' COMMENT '来源表',
    computed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '计算时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_shop_profile_snapshot (marketplace, seller_name, batch_date, variation_mode),
    KEY idx_shop_profile_batch (marketplace, batch_date),
    KEY idx_shop_profile_abc (marketplace, batch_date, abc_count),
    KEY idx_shop_profile_seller (seller_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='店铺画像快照';

CREATE TABLE IF NOT EXISTS shop_profile_category (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    marketplace VARCHAR(16) NOT NULL COMMENT '站点/国家',
    seller_name VARCHAR(255) NOT NULL COMMENT '店铺名',
    batch_date VARCHAR(64) NOT NULL COMMENT '数据批次',
    variation_mode VARCHAR(8) NOT NULL DEFAULT 'Y' COMMENT 'Y=不含变体父体口径,N=含变体',
    sales_tier VARCHAR(16) NOT NULL COMMENT 'A/B/C/D/UNKNOWN/ABC',
    category_key VARCHAR(255) NOT NULL COMMENT '类目键，第一版为榜单末级类目',
    product_count INT NOT NULL DEFAULT 0 COMMENT '商品数',
    units_sum BIGINT NOT NULL DEFAULT 0 COMMENT '销量合计',
    units_avg DECIMAL(18,2) NULL COMMENT '销量平均值',
    units_median DECIMAL(18,2) NULL COMMENT '销量中位数，预留',
    source_table VARCHAR(64) NOT NULL DEFAULT 'deng_zong_shop' COMMENT '来源表',
    computed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '计算时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_shop_profile_category (marketplace, seller_name, batch_date, variation_mode, sales_tier, category_key),
    KEY idx_shop_profile_category_batch (marketplace, batch_date, sales_tier),
    KEY idx_shop_profile_category_key (category_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='店铺画像类目结构';

CREATE TABLE IF NOT EXISTS shop_profile_baseline (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    baseline_code VARCHAR(64) NOT NULL COMMENT '基线编码',
    baseline_name VARCHAR(255) NOT NULL COMMENT '基线名称',
    baseline_type VARCHAR(64) NOT NULL COMMENT 'ZHENG/OWN_GOOD/METHOD_HIGH_HIT/CATEGORY_SPECIAL',
    marketplace_scope VARCHAR(255) NULL COMMENT '适用站点范围',
    category_scope VARCHAR(255) NULL COMMENT '适用类目范围',
    shop_count INT NOT NULL DEFAULT 0 COMMENT '成员店铺数',
    metric_summary_json JSON NULL COMMENT '基线画像统计摘要',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态',
    created_by VARCHAR(64) NULL COMMENT '创建人/来源',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_shop_profile_baseline_code (baseline_code),
    KEY idx_shop_profile_baseline_type (baseline_type, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='店铺画像基线';

CREATE TABLE IF NOT EXISTS shop_profile_baseline_member (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    baseline_code VARCHAR(64) NOT NULL COMMENT '基线编码',
    marketplace VARCHAR(16) NOT NULL COMMENT '站点/国家',
    seller_name VARCHAR(255) NOT NULL COMMENT '店铺名',
    seller_id VARCHAR(128) NULL COMMENT '卖家ID',
    source_reason VARCHAR(255) NULL COMMENT '加入原因',
    weight DECIMAL(10,4) NOT NULL DEFAULT 1 COMMENT '成员权重',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态',
    added_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '加入时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_shop_profile_baseline_member (baseline_code, marketplace, seller_name),
    KEY idx_shop_profile_baseline_member_shop (marketplace, seller_name),
    CONSTRAINT fk_shop_profile_baseline_member_code
        FOREIGN KEY (baseline_code) REFERENCES shop_profile_baseline (baseline_code)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='店铺画像基线成员';

CREATE TABLE IF NOT EXISTS shop_profile_positioning_result (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    baseline_code VARCHAR(64) NOT NULL COMMENT '基线编码',
    baseline_name VARCHAR(255) NOT NULL COMMENT '基线名称',
    marketplace VARCHAR(16) NOT NULL COMMENT '站点/国家',
    seller_name VARCHAR(255) NOT NULL COMMENT '店铺名',
    seller_id VARCHAR(128) NULL COMMENT '卖家ID',
    batch_date VARCHAR(64) NOT NULL COMMENT '数据批次',
    variation_mode VARCHAR(8) NOT NULL DEFAULT 'Y' COMMENT 'Y=不含变体父体口径,N=含变体',
    product_count INT NOT NULL DEFAULT 0 COMMENT '商品数',
    a_count INT NOT NULL DEFAULT 0 COMMENT 'A层商品数',
    b_count INT NOT NULL DEFAULT 0 COMMENT 'B层商品数',
    c_count INT NOT NULL DEFAULT 0 COMMENT 'C层商品数',
    d_count INT NOT NULL DEFAULT 0 COMMENT 'D层商品数',
    unknown_count INT NOT NULL DEFAULT 0 COMMENT '未知销量商品数',
    ab_count INT NOT NULL DEFAULT 0 COMMENT 'A+B 强候选池',
    abc_count INT NOT NULL DEFAULT 0 COMMENT 'A+B+C 稳定盘',
    a_ratio DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT 'A占比',
    ab_ratio DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT 'A+B占比',
    abc_ratio DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT 'A+B+C占比',
    d_ratio DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT 'D占比',
    top_a_category VARCHAR(255) NULL COMMENT 'A层最高频类目',
    top_abc_category VARCHAR(255) NULL COMMENT 'ABC最高频类目',
    top_d_category VARCHAR(255) NULL COMMENT 'D层最高频类目',
    profile_type VARCHAR(64) NULL COMMENT '结构标签',
    baseline_shop_count INT NOT NULL DEFAULT 0 COMMENT '基线成员快照数',
    baseline_avg_product_count DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '基线平均商品数',
    baseline_avg_a_ratio DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT '基线平均A占比',
    baseline_avg_ab_ratio DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT '基线平均AB占比',
    baseline_avg_abc_ratio DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT '基线平均ABC占比',
    baseline_avg_d_ratio DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT '基线平均D占比',
    category_match_score DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT '类目结构匹配分',
    similarity_score DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT '店铺画像相似度分',
    positioning_label VARCHAR(64) NULL COMMENT '定位标签',
    profile_advice VARCHAR(512) NULL COMMENT '解释建议',
    computed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '计算时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_shop_profile_positioning (baseline_code, marketplace, seller_name, batch_date, variation_mode),
    KEY idx_shop_profile_positioning_score (baseline_code, batch_date, similarity_score),
    KEY idx_shop_profile_positioning_shop (marketplace, seller_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='店铺画像基线定位结果';

CREATE TABLE IF NOT EXISTS product_family_group (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    family_code VARCHAR(64) NOT NULL COMMENT '商品族编码',
    marketplace VARCHAR(16) NULL COMMENT '站点/国家，可为空表示跨站点',
    family_name VARCHAR(255) NULL COMMENT '商品族名称',
    seed_asin VARCHAR(32) NULL COMMENT '种子ASIN',
    seed_sales_tier VARCHAR(16) NULL COMMENT '种子销量等级',
    category_key VARCHAR(255) NULL COMMENT '类目键',
    title_signature VARCHAR(512) NULL COMMENT '标题核心签名',
    price_min DECIMAL(18,2) NULL COMMENT '价格带下限',
    price_max DECIMAL(18,2) NULL COMMENT '价格带上限',
    evidence_json JSON NULL COMMENT '商品族证据摘要',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态',
    computed_at DATETIME NULL COMMENT '计算时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_product_family_code (family_code),
    KEY idx_product_family_seed (marketplace, seed_asin),
    KEY idx_product_family_category (marketplace, category_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品族证据组';

CREATE TABLE IF NOT EXISTS product_family_member (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    family_code VARCHAR(64) NOT NULL COMMENT '商品族编码',
    marketplace VARCHAR(16) NOT NULL COMMENT '站点/国家',
    asin VARCHAR(32) NOT NULL COMMENT 'ASIN',
    parent_asin VARCHAR(32) NULL COMMENT '父ASIN',
    seller_name VARCHAR(255) NULL COMMENT '店铺名',
    seller_id VARCHAR(128) NULL COMMENT '卖家ID',
    source_table VARCHAR(64) NOT NULL COMMENT '来源表',
    source_batch VARCHAR(64) NOT NULL DEFAULT '' COMMENT '来源批次',
    match_type VARCHAR(64) NOT NULL COMMENT 'SAME_ASIN/PARENT_ASIN/TITLE_SIMILAR/ELEMENT_CARRIER',
    match_score DECIMAL(10,4) NULL COMMENT '相似度分数',
    sales_tier VARCHAR(16) NULL COMMENT '销量等级',
    units INT NULL COMMENT '月销量',
    listing_days INT NULL COMMENT '上架天数',
    category_key VARCHAR(255) NULL COMMENT '类目键',
    evidence_json JSON NULL COMMENT '命中证据',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_product_family_member (family_code, marketplace, asin, source_table, source_batch),
    KEY idx_product_family_member_asin (marketplace, asin),
    KEY idx_product_family_member_seller (marketplace, seller_name),
    CONSTRAINT fk_product_family_member_code
        FOREIGN KEY (family_code) REFERENCES product_family_group (family_code)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品族证据成员';

CREATE TABLE IF NOT EXISTS method_product_hit (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    method_id VARCHAR(32) NOT NULL COMMENT '方法卡ID',
    marketplace VARCHAR(16) NOT NULL COMMENT '站点/国家',
    asin VARCHAR(32) NOT NULL COMMENT 'ASIN',
    parent_asin VARCHAR(32) NULL COMMENT '父ASIN',
    seller_name VARCHAR(255) NULL COMMENT '店铺名',
    seller_id VARCHAR(128) NULL COMMENT '卖家ID',
    source_table VARCHAR(64) NOT NULL COMMENT '来源表',
    source_batch VARCHAR(64) NOT NULL DEFAULT '' COMMENT '来源批次',
    hit_reason_json JSON NULL COMMENT '命中原因',
    rule_snapshot_json JSON NULL COMMENT '规则快照',
    hit_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE/EXPIRED',
    computed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '计算时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_method_product_hit (method_id, marketplace, asin, source_table, source_batch),
    KEY idx_method_product_hit_shop (method_id, marketplace, seller_name, hit_status),
    KEY idx_method_product_hit_asin (marketplace, asin)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='方法卡商品命中缓存';
