export const AI_LISTING_TASK_STATUS = {
  QUEUED: 100,
  KEYWORD_SCORING_RUNNING: 110,
  KEYWORD_SCORING_RETRYING: 120,
  KEYWORD_SCORING_SUCCEEDED: 190,
  LANGGRAPH_RUNNING: 200,
  LANGGRAPH_RETRYING: 210,
  LANGGRAPH_SUCCEEDED: 290,
  PERSISTING: 300,
  SUCCEEDED: 390,
  FAILED: 900,
  CANCELLED: 990,
} as const;

export type AiListingTaskStatusCode =
  (typeof AI_LISTING_TASK_STATUS)[keyof typeof AI_LISTING_TASK_STATUS];

/** 人工审核终态 stage（status 仍为 390） */
export const AI_LISTING_REVIEW_TERMINAL_STAGES = new Set([
  'review_approved',
  'accepted',
  'review_closed',
]);

export const AI_LISTING_REVIEW_CLOSED_STAGE = 'review_closed';

export function normalizeAiListingStage(stage?: string | null): string {
  return String(stage || '')
    .trim()
    .toLowerCase();
}

export function isAiListingReviewTerminalStage(stage?: string | null): boolean {
  return AI_LISTING_REVIEW_TERMINAL_STAGES.has(normalizeAiListingStage(stage));
}

export function isAiListingReviewClosedStage(stage?: string | null): boolean {
  return normalizeAiListingStage(stage) === AI_LISTING_REVIEW_CLOSED_STAGE;
}

export const AI_LISTING_TERMINAL_STATUS = new Set<number>([
  AI_LISTING_TASK_STATUS.SUCCEEDED,
  AI_LISTING_TASK_STATUS.FAILED,
  AI_LISTING_TASK_STATUS.CANCELLED,
]);

export const AI_LISTING_ACTIVE_STATUS = new Set<number>([
  AI_LISTING_TASK_STATUS.QUEUED,
  AI_LISTING_TASK_STATUS.KEYWORD_SCORING_RUNNING,
  AI_LISTING_TASK_STATUS.KEYWORD_SCORING_RETRYING,
  AI_LISTING_TASK_STATUS.KEYWORD_SCORING_SUCCEEDED,
  AI_LISTING_TASK_STATUS.LANGGRAPH_RUNNING,
  AI_LISTING_TASK_STATUS.LANGGRAPH_RETRYING,
  AI_LISTING_TASK_STATUS.LANGGRAPH_SUCCEEDED,
  AI_LISTING_TASK_STATUS.PERSISTING,
]);

export const AI_LISTING_ALLOWED_TRANSITIONS: Record<number, number[]> = {
  [AI_LISTING_TASK_STATUS.QUEUED]: [
    AI_LISTING_TASK_STATUS.KEYWORD_SCORING_RUNNING,
    AI_LISTING_TASK_STATUS.FAILED,
    AI_LISTING_TASK_STATUS.CANCELLED,
  ],
  [AI_LISTING_TASK_STATUS.KEYWORD_SCORING_RUNNING]: [
    AI_LISTING_TASK_STATUS.KEYWORD_SCORING_RETRYING,
    AI_LISTING_TASK_STATUS.KEYWORD_SCORING_SUCCEEDED,
    AI_LISTING_TASK_STATUS.LANGGRAPH_RUNNING,
    AI_LISTING_TASK_STATUS.FAILED,
    AI_LISTING_TASK_STATUS.CANCELLED,
  ],
  [AI_LISTING_TASK_STATUS.KEYWORD_SCORING_RETRYING]: [
    AI_LISTING_TASK_STATUS.KEYWORD_SCORING_RUNNING,
    AI_LISTING_TASK_STATUS.FAILED,
    AI_LISTING_TASK_STATUS.CANCELLED,
  ],
  [AI_LISTING_TASK_STATUS.KEYWORD_SCORING_SUCCEEDED]: [
    AI_LISTING_TASK_STATUS.KEYWORD_SCORING_RUNNING,
    AI_LISTING_TASK_STATUS.LANGGRAPH_RUNNING,
    AI_LISTING_TASK_STATUS.CANCELLED,
  ],
  [AI_LISTING_TASK_STATUS.LANGGRAPH_RUNNING]: [
    AI_LISTING_TASK_STATUS.KEYWORD_SCORING_RUNNING,
    AI_LISTING_TASK_STATUS.LANGGRAPH_RETRYING,
    AI_LISTING_TASK_STATUS.LANGGRAPH_SUCCEEDED,
    AI_LISTING_TASK_STATUS.SUCCEEDED,
    AI_LISTING_TASK_STATUS.FAILED,
    AI_LISTING_TASK_STATUS.CANCELLED,
  ],
  [AI_LISTING_TASK_STATUS.LANGGRAPH_RETRYING]: [
    AI_LISTING_TASK_STATUS.KEYWORD_SCORING_RUNNING,
    AI_LISTING_TASK_STATUS.LANGGRAPH_RUNNING,
    AI_LISTING_TASK_STATUS.FAILED,
    AI_LISTING_TASK_STATUS.CANCELLED,
  ],
  [AI_LISTING_TASK_STATUS.LANGGRAPH_SUCCEEDED]: [
    AI_LISTING_TASK_STATUS.KEYWORD_SCORING_RUNNING,
    AI_LISTING_TASK_STATUS.PERSISTING,
    AI_LISTING_TASK_STATUS.CANCELLED,
  ],
  [AI_LISTING_TASK_STATUS.PERSISTING]: [
    AI_LISTING_TASK_STATUS.KEYWORD_SCORING_RUNNING,
    AI_LISTING_TASK_STATUS.SUCCEEDED,
    AI_LISTING_TASK_STATUS.FAILED,
    AI_LISTING_TASK_STATUS.CANCELLED,
  ],
  [AI_LISTING_TASK_STATUS.SUCCEEDED]: [
    AI_LISTING_TASK_STATUS.KEYWORD_SCORING_RUNNING,
  ],
  [AI_LISTING_TASK_STATUS.FAILED]: [
    AI_LISTING_TASK_STATUS.KEYWORD_SCORING_RUNNING,
  ],
  [AI_LISTING_TASK_STATUS.CANCELLED]: [
    AI_LISTING_TASK_STATUS.KEYWORD_SCORING_RUNNING,
  ],
};

export function stageByStatus(status: number): string {
  if (status >= 900)
    return status === AI_LISTING_TASK_STATUS.CANCELLED ? 'cancelled' : 'failed';
  if (status >= 390) return 'succeeded';
  if (status >= 300) return 'persisting';
  if (status >= 290) return 'langgraph_succeeded';
  if (status >= 210) return 'langgraph_retrying';
  if (status >= 200) return 'langgraph_running';
  if (status >= 190) return 'keyword_scoring_succeeded';
  if (status >= 120) return 'keyword_scoring_retrying';
  if (status >= 110) return 'keyword_scoring_running';
  return 'queued';
}

export function isTransitionAllowed(
  fromStatus: number,
  toStatus: number
): boolean {
  const allowed = AI_LISTING_ALLOWED_TRANSITIONS[fromStatus] || [];
  return allowed.includes(toStatus);
}
